document.addEventListener('DOMContentLoaded', () => {
    const user = JSON.parse(sessionStorage.getItem('user'));
    if (!user) {
        window.location.href = 'login.html';
        return;
    }
    const pending = JSON.parse(sessionStorage.getItem('pendingOrder'));
    if (!pending || !pending.items || pending.items.length === 0) {
        window.location.href = 'student.html';
        return;
    }
    renderOrderSummary(pending);
});

function renderOrderSummary(pending) {
    const summaryContainer = document.getElementById('orderItems');
    const totalDisplay = document.getElementById('payTotal');
    if (totalDisplay) {
        totalDisplay.textContent = `₹${pending.total}`;
    }
    if (summaryContainer) {
        summaryContainer.innerHTML = pending.items.map(item => `
            <div class="summary-item" style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                <span>${item.dish_name} x ${item.qty}</span>
                <span style="font-weight:600;">₹${item.price * item.qty}</span>
            </div>
        `).join('');
    }
}

async function processPayment() {
    const pending = JSON.parse(sessionStorage.getItem('pendingOrder'));
    const payBtn = document.querySelector('.btn-pay');

    if (payBtn.disabled) return;

    try {
        payBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Creating Order...';
        payBtn.disabled = true;

        // ---> DATABASE FIX: Generate a unique ID for MongoDB <---
        const generatedOrderId = "ORD" + Date.now() + Math.floor(Math.random() * 1000);

        // 1. Create the order in your database FIRST
        const orderPayload = {
            order_id: generatedOrderId,       // <-- Required by your Order schema
            total_amount: pending.total,      // <-- Required by your Order schema
            items: pending.items.map(i => ({
                dish_name: i.dish_name,
                quantity: i.qty,
                price: i.price
            }))
        };

        const orderRes = await api.placeOrder(orderPayload);

        // Safely extract the Order ID from your backend's response
        const orderId = orderRes.order?.order_id || orderRes.data?.order?.order_id || orderRes.order_id || generatedOrderId;

        if (!orderId) {
            throw new Error("Could not retrieve Order ID from the server.");
        }

        payBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Connecting...';

        // 2. Ask backend to create a Razorpay Order using the new order_id
        const paymentRes = await api.createRazorpayOrder({ order_id: orderId });

        const razorpayOrder = paymentRes.razorpay_order || paymentRes.data?.razorpay_order;
        const paymentId = paymentRes.payment_id || paymentRes.data?.payment_id;

        // ---> ENV FIX: Extract the dynamic Key ID sent from the backend <---
        const dynamicKeyId = paymentRes.key_id || paymentRes.data?.key_id;

        if (!dynamicKeyId) {
            throw new Error("Razorpay Key ID missing from server response.");
        }

        // 3. Configure the Razorpay Popup Window
        const options = {
            key: dynamicKeyId, // <-- USING THE DYNAMIC KEY HERE
            amount: razorpayOrder.amount,
            currency: "INR",
            name: "College Food Court",
            description: `Order #${orderId}`,
            order_id: razorpayOrder.id,

            // 4. This runs automatically if the student successfully pays
            handler: async function (response) {
                try {
                    payBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Verifying...';

                    // Send the proof of payment to your backend's verify route
                    const verifyRes = await api.verifyRazorpayPayment({
                        razorpay_order_id: response.razorpay_order_id,
                        razorpay_payment_id: response.razorpay_payment_id,
                        razorpay_signature: response.razorpay_signature,
                        payment_id: paymentId // Your backend explicitly requires this!
                    });

                    // 5. Success! Show the QR code screen
                    sessionStorage.removeItem('pendingOrder');

                    // Hide the checkout form
                    const paymentContainer = document.querySelector('.payment-container');
                    if (paymentContainer) paymentContainer.style.display = 'none';

                    // Update the success screen with the real Order ID
                    document.getElementById('finalOrderNumber').innerText = `#${orderId}`;

                    // Display the real QR code generated by your backend
                    const qrImageSrc = verifyRes.qr_code || verifyRes.data?.qr_code;
                    if (qrImageSrc) {
                        document.getElementById('generatedQR').src = qrImageSrc;
                    }

                    document.getElementById('successScreen').style.display = 'block';

                } catch (verifyErr) {
                    console.error("Verification Error:", verifyErr);
                    alert("Payment completed, but verification failed. Please contact the canteen admin.");
                    payBtn.innerHTML = 'Confirm & Pay';
                    payBtn.disabled = false;
                }
            },
            theme: { color: "#10b981" }
        };

        // Open the Razorpay Modal
        const rzp = new Razorpay(options);

        rzp.on('payment.failed', function (response) {
            alert("Payment Failed: " + response.error.description);
            payBtn.innerHTML = 'Confirm & Pay';
            payBtn.disabled = false;
        });

        rzp.open();

    } catch (err) {
        payBtn.innerHTML = 'Confirm & Pay';
        payBtn.disabled = false;

        const errorMsg = err.response?.data?.message || err.message || "Failed to initiate payment. Please try again.";
        alert(errorMsg);
        console.error("Payment Flow Error:", err);
    }
}